# pytest configuration file
[tool.pytest.ini_options]

--show-capture="no"

# logging configuration
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s"   # add (%(filename)s:%(lineno)s) if we want to have line in code referenced
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_file = "pytest.log"
log_file_level = "DEBUG"
log_file_format = "%(asctime)s [%(levelname)8s] %(message)s"  # add (%(filename)s:%(lineno)s) if we want to have line in code referenced
log_file_date_format = "%Y-%m-%d %H:%M:%S"
